[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["packages*", "apps.api*"]
exclude = ["apps.web*"]

[project]
name = "hax"
version = "0.1.0"
description = "Local dev configuration for hax."
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
  "pre-commit>=3.7.0",
  "ruff>=0.6.0",
]

[tool.ruff]
line-length = 88
target-version = "py311"
fix = true
respect-gitignore = true
src = ["apps", "packages"]
extend-exclude = [
  "apps/web",
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["apps", "packages"]
